(function sm(){function Ea(z,A,G,fa){function Ga(Ra){return Ra instanceof G?Ra:new G(function(gb){gb(Ra)})}return new (G||(G=v))(function(Ra,gb){function yb(Hb){try{Lb(fa.next(Hb))}catch(l){gb(l)}}function Gb(Hb){try{Lb(fa.throw(Hb))}catch(l){gb(l)}}function Lb(Hb){Hb.done?Ra(Hb.value):Ga(Hb.value).then(yb,Gb)}Lb((fa=fa.apply(z,A||[])).next())})}function hb(z){return Wc&&(Tc.da(self,Wc),Wc=null),new v(function(A){Wc=Tc.$(self,function(G,fa,Ga){"pair"!==G.Z||"pair-id"!==G.query||(z.send(new sc({Z:"pair",
query:"pair-ack",result:G.result})),Ga(),A())});z.send(new sc({Z:"pair",query:"pair-req"}))})}function cb(z){return new v(function(A){z.vb(function(G){"handshake"===G.Z&&["connect-ack","connect-pair"].includes(G.query)&&A({$e:"connect-pair"===G.query})})})}function $a(z){return new v(function(A,G){setTimeout(G,z)})}function Ca(z){return Ea(this,void 0,void 0,function*(){let A=new sc({Z:"handshake",query:"connect-req"}),G=new Tc;Tc.I(z,A,{transfer:[G.G]});try{let fa=yield v.race([cb(G),$a(1E3)]);fa&&
fa.$e&&(yield v.race([hb(G),$a(1E3)]))}catch(fa){throw G.port.close(),Error("timeout");}return G})}function Na(z){return Ea(this,arguments,void 0,function*(A,G=15){let fa=0;for(;fa<G;)try{return yield Ca(A)}catch(Ga){fa++}throw Error("connect handshake failed");})}function Ja(z,A,G){return Ea(this,void 0,void 0,function*(){if("undefined"!=typeof G.result){var {resolve:fa}=Pc.get(G.id)||{};(Pc.delete(G.id),fa)&&fa(G.result)}else if(fd.has(G.Z)){var Ga=fd.get(G.Z);if(Ga){fa=Dc.includes(Ga);Ga=yield Ga.apply(A,
[z,...G.query]);let [Ra,gb]=fa?Ga:[Ga,[]];G.pf(Ra);A.send(G,gb)}}})}function ab(){Oc=new WeakMap;Pc=new Map;fd=new Map}function va(){Oc&&Pc&&fd||ab()}function ua(){return Ea(this,arguments,void 0,function*(z=!1){if(ab(),Fa()||z){let A=self;try{let G=yield Na(A);Oc.set(A,G);G.vb(function(fa){Ja(A,G,fa)})}catch(G){return{initialized:!1,Zd:`${G}`}}}else if(self.parent!==self){let A=self.parent;try{let G=yield Na(A,2);Oc.set(A,G);G.vb(function(fa){Ja(A,G,fa)})}catch(G){}}return{initialized:!0,Zd:""}})}
function pa(z,A,{transfer:G=!1}={}){va();fd.set(z,A);G&&Dc.push(A)}function wa(z,A,G){let fa=new sc({Z:A,query:G});return new v(function(Ga,Ra){Pc.set(fa.id,{resolve:Ga,reject:Ra});z.send(fa)})}function La(z,...A){va();let G=Oc.get(self);return G?wa(G,z,A):v.resolve()}function da(){let z=Fc.dT_,A=z&&z.iIO,{port1:G,port2:fa}=new MessageChannel,Ga=new ArrayBuffer(1);return new v(function(Ra){G.onmessage=function({data:gb}){Ra(A?A(gb,26):gb instanceof ArrayBuffer);G.close()};fa.postMessage(Ga,[Ga])})}
function Fa(){return"undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope}function oa(){let z=Fc.dT_;return{version:"10343260715123811",ac:z.bcv("ac"),app:z.scv("app"),postfix:z.scv("postfix")}}function Ua(z,A){return Ea(this,arguments,void 0,function*(G,fa,Ga=1){try{return yield v.race([G(),new v(function(Ra,gb){setTimeout(gb,fa)})])}catch(Ra){if(0<Ga)return Ua(G,fa,Ga-1);throw Ra;}})}function W(){return Ea(this,void 0,void 0,function*(){let z=Fc.dT_;if(z&&!Fa()&&Fc.parent!==Fc){var A=
z.tdto();if(!A||z===A)try{let G=oa();yield Ua(()=>{var fa=[G];va();let Ga=Oc.get(self.parent);return Ga?wa(Ga,"detectSubframe",fa):v.resolve()},1E3)}catch(G){}}})}function ea(z){if(z)return K.get(z)}function Y(){K.clear();xa=[];C.clear()}function Q(z){return!!z&&xa.some(function(A){return A.id===`${z}.1`})}function ja(z,A){({values:z}=z.find(A,void 0,!0));return z.filter(G=>G).map(ea).filter(function(G){return void 0!==G})}function ya(z,A,G){if(z.Nc()<A.from)return null;z=z.find(A,G);return 0===z.values.length?
null:z}function Wa(z,A,G){if(z.Uc<A.from)return null;let fa=[];return z.attributes.forEach(function(Ga){if(!(Ga.$a<A.from)){var Ra=ya(Ga.values,A,G);Ra&&fa.push({name:Ga.name,entries:Ra})}}),0===fa.length?null:fa}function U(z,A){z.values.clear(A);z.Ib.clear(A);z.wb.clear(A);z.fe.clear(A);z.ed.clear(A);z.attributes.forEach(function(G){G.values.clear(A)})}function D(){return Math.round(Oa+Ha.now())}function R(z){La("perfstart",{i:"compress",t:D(),m:"start"});var A=new Ba.kg(z);let G=new Uint8Array(A.rh());
A=A.Bg(G);return La("perfend",{i:"compress",t:D(),m:"end",d:[["in",z.byteLength],["out",A]],a:!0}),G.buffer.slice(0,A)}function B(z,A){z=R(A);return new Uint8Array(z)}function M(z){let A=z+"";return vb.forEach(function(G){A=A.replace(G[0],"\x00"+G[1])}),A}function I(z,A=Kb){La("perfstart",{i:"serialize",t:D(),m:"start"});Ta=Ta||new Uint8Array((new TextEncoder).encode("\u0001"));let G={entries:[],size:0},fa=[G];z.forEach(function(gb){var yb={ga:"",Ya:""};yb.ga+=gb.id+"\u0002";gb.name?yb.ga+=M(gb.name)+
"\u0002":yb.ga+="\u0002";gb.type&&"html"!==gb.type&&(yb.ga+=M(gb.type));gb.values&&ca(gb.values,"\u0005",yb);gb.attributes&&qa(gb.attributes,yb);gb.Ib&&ca(gb.Ib,"\u0011",yb);gb.wb&&ca(gb.wb,"\u0012",yb);gb=Uint8Array;yb=`${yb.ga}${"\u0001"}${yb.Ya.slice(0,-1)}`;yb=(new TextEncoder).encode(yb);gb=new gb(yb);yb=gb.byteLength+Ta.byteLength;0<G.size&&G.size+yb>A&&(G={entries:[],size:0},fa.push(G));G.entries.push(gb);G.size+=yb});let Ga=0,Ra=fa.map(function(gb){let yb=new Uint8Array(gb.size-Ta.byteLength),
Gb=0;return gb.entries.forEach(function(Lb){yb.set(Lb,Gb);Gb+=Lb.byteLength;Gb!==yb.byteLength&&(yb.set(Ta,Gb),Gb+=Ta.byteLength)}),Ga+=yb.byteLength,yb});return La("perfend",{i:"serialize",t:D(),m:"end",d:[["nodes",z.length],["out",Ga]],a:!0}),Ra}function ca(z,A,G){G.ga+=A;z.Lb.forEach(function(fa,Ga){let Ra=z.values[Ga];G.Ya+=fa;"string"==typeof Ra?""!==Ra?G.ga+=M(Ra):G.ga+="\u0003":null===Ra||"undefined"==typeof Ra?G.ga+="\u0014":(G.ga+="\u0004",G.Ya+="\u0002"+Ra);Ga!==z.Lb.length-1&&(G.ga+="\u0002");
G.Ya+="\u0002"})}function qa(z,A){A.ga+="\u0006";z.forEach(function(G,fa){A.ga+=M(G.name)+"\u0002";G.entries.Lb.forEach(function(Ga,Ra){A.Ya+=Ga;Ga=G.entries.values[Ra];"string"==typeof Ga?""!==Ga?A.ga+=M(Ga):A.ga+="\u0003":null===Ga||"undefined"==typeof Ga?A.ga+="\u0014":(A.ga+="\u0004",A.Ya+="\u0002"+Ga);Ra!==G.entries.Lb.length-1&&(A.ga+="\u0002");A.Ya+="\u0002"});fa!==z.length-1&&(A.ga+="\u0006")})}function ob(z,A,G){function fa(Ra){G(Ra)&&Ga.unshift(...A(Ra.ed))}let Ga=[z];for(z=new Set;Ga.length;){let Ra=
Ga.splice(0,Ga.length);for(let gb of Ra)Za(gb,z,A,fa)}}function Za(z,A,G,fa){z=[[z]];let Ga=new Set;for(;z.length;){let Ra=z.pop(),gb=null==Ra?void 0:Ra.shift();if(!Ra||!gb)continue;if(A.has(gb)){z.push(Ra);continue}let yb=Ga.has(gb)?[]:G(gb.wb);yb.length?(Ga.add(gb),Ra.push(gb),z.push(Ra,yb)):(z.push(Ra),A.add(gb),fa(gb))}}function nb(z){ka.delete(z);if(!(z.Sg()<pb.from)){var A=z.Yd>=pb.from,G=ya(z.values,pb),fa=Wa(z,pb,Ub),Ga=ya(z.Ib,pb,500),Ra=ya(z.wb,pb,500);if("#text"===z.name&&null!==G){let gb=
G.values[0];if(gb.length>Ub){xb(z,fa,Ga,Ra,gb,G.Lb[0]);return}}!(A||G||fa||Ga||Ra)||(fc.push({id:z.id,type:A?z.type:"html",name:A?z.name:void 0,values:G,attributes:fa,Ib:Ga,wb:Ra}),z.Vf())}}function xb(z,A,G,fa,Ga,Ra){if(Ga){var {id:gb,type:yb,name:Gb}=z;Ga=Qb(Ga,Ub);var Lb=Ga.length-1;Ga.forEach(function(Hb,l){fc.push({id:gb+"s"+l,type:yb,name:Gb,values:{Lb:[Ra],values:[Hb]},attributes:A,Ib:G,wb:l===Lb?fa:{Lb:[0],values:[gb+"s"+(l+1)]}})});z.Vf()}}function Qb(z,A){let G=[];for(let fa=0;fa<z.length;fa+=
A)G.push(z.slice(fa,fa+A));return G}function $b(z){return z.$a<pb.from||(nb(z),"iframe"===z.name)?!1:(U(z,pb.eb),!0)}function qc(z,A){z=ea("1");if(!z||z.Xd<Ub&&A-Cb<1E3*Ec)return[null,[]];Cb=A;let G=[];return xa.forEach(function(fa){fc=[];let Ga=(fa.$d||0)+1;pb={from:Ga,eb:Math.max(A,Ga)};La("perfstart",{i:"collect",t:D(),m:"start"});ob(fa,function(Ra){return ja(Ra,pb)},$b);Array.from(ka.values()).forEach(nb);La("perfend",{i:"collect",t:D(),m:"end",d:[["nodes",fc.length]],a:!0});fa.$d=Math.min(fa.$a,
A-1);Array.from(C.values()).forEach(function(Ra){Ra.Yd<pb.from||Ra.Yd>A||(Ra.$d||0)>=Ra.$a||(nb(Ra),Ra.$d=Math.min(Ra.$a,A-1))});aa(G,{Gb:fc,from:pb.from,eb:pb.eb})}),Aa(G)}function mc(){return Ea(this,void 0,void 0,function*(){Cb=0;pa("collectorConfig",function(z,A){return Kb=A.uh,Ub=.9*Kb,Ec=A.Rh,A});Bc=yield da();pa("collect",qc,{transfer:!0})})}function aa(z,A){if(A.Gb.length){var G=z.find(function({from:fa}){return fa===A.from});G?(G.eb=Math.max(G.eb,A.eb),G.Gb=G.Gb.concat(A.Gb)):z.push(A)}}
function Aa(z){let A=[],G=[];for(let {Gb:fa,from:Ga,eb:Ra}of z)for(let gb of I(fa))z=R(gb),Bc&&A.push(z),G.push({data:Bc?z:Array.prototype.slice.call(new Uint8Array(z)),from:Ga,eb:Ra});return 0===G.length?[null,[]]:[G,A]}function lb(z,A="*"){return null!==z&&""!==z?z.replace(/[^- :\u2013\/\u2014._;,()=!?|<>+%\u20ac$\u00a2\u00a5\u00a3\u20bd\u5143\u20a8\u20bf'"@&\u3002\u3001\]\[\n\r\\]/g,A):z}function Nc(z,A){z&&(A.prototype.toJSON=z)}function pc(z){let A=new Map,G=Date.prototype.toJSON;[Number,Boolean,
String,Array,Object].forEach(function(fa){A.set(fa,fa.prototype.toJSON);delete fa.prototype.toJSON});Date.prototype.toJSON=ld;try{return JSON.stringify(z)}finally{A.forEach(Nc),Date.prototype.toJSON=G}}function Rb(z,A){if((z=ea(z.Y))&&z.id){ka.add(z);var G=ea(z.getParent()),fa=ea(z.Lf()),Ga=ea(z.Nf());Ga&&fa?(Ga.Sb(fa.id,A),fa.Tb(Ga.id,A)):Ga?Ga.Sb(null,A):(fa&&fa.Tb(null,A),G&&G.Kf()===z.id&&G.mf(fa?fa.id:null,A));z.nf(null,A);z.Sb(null,A);z.Tb(null,A)}}function Sb(z,A){K.delete(A)}function oc(z){z=
ea(z);if(!z)return!1;if("css.create"===z.name||"style"===z.name)return!0;if("#text"!==z.name)return!1;z=ea(z.getParent());return!(!z||"style"!==z.name&&"css.create"!==z.name)}function ec(z){let {Y:A,type:G}=z.set[0];return G===ad.$&&void 0!==A&&"1"===A.split(".").pop()}function cc(z){({Y:z}=z.set[0]);return z&&z.includes(".")?z.slice(0,z.lastIndexOf(".")):""}function T(z,A,G){Array.from(K.keys()).forEach(function(fa){"string"!=typeof fa||fa.includes("m")||A.includes(fa)||(!z&&!fa.includes(".")||fa.startsWith(z+
".")&&fa.lastIndexOf(".")===z.length)&&!oc(fa)&&Rb(new ad(ad.I,{Y:fa}),G)})}function ha(z,A){let G=td.G(A);if(G&&G.size){var fa=ec(G),Ga=new Set;G.forEach(function(Ra){let {type:gb,Y:yb}=Ra;jd[gb]&&(fa&&void 0!==yb&&Ga.add(yb),jd[gb](Ra,G.time))});fa&&T(cc(G),Array.from(Ga),G.time)}}function Pa(z,A,G,fa,Ga){let Ra,gb,yb,Gb,Lb,Hb,l,r;let q;for(var F;64<=Ga;){Ra=A[0];gb=A[1];yb=A[2];Gb=A[3];Lb=A[4];Hb=A[5];l=A[6];r=A[7];for(q=0;16>q;q++)F=fa+4*q,z[q]=(G[F]&255)<<24|(G[F+1]&255)<<16|(G[F+2]&255)<<8|
G[F+3]&255;for(q=16;64>q;q++){var L=z[q-2];F=(L>>>17|L<<15)^(L>>>19|L<<13)^L>>>10;L=z[q-15];L=(L>>>7|L<<25)^(L>>>18|L<<14)^L>>>3;z[q]=(F+z[q-7]|0)+(L+z[q-16]|0)}for(q=0;64>q;q++)F=(((Lb>>>6|Lb<<26)^(Lb>>>11|Lb<<21)^(Lb>>>25|Lb<<7))+(Lb&Hb^~Lb&l)|0)+(r+(gd[q]+z[q]|0)|0)|0,L=((Ra>>>2|Ra<<30)^(Ra>>>13|Ra<<19)^(Ra>>>22|Ra<<10))+(Ra&gb^Ra&yb^gb&yb)|0,r=l,l=Hb,Hb=Lb,Lb=Gb+F|0,Gb=yb,yb=gb,gb=Ra,Ra=F+L|0;A[0]+=Ra;A[1]+=gb;A[2]+=yb;A[3]+=Gb;A[4]+=Lb;A[5]+=Hb;A[6]+=l;A[7]+=r;fa+=64;Ga-=64}return fa}function ia(z,
A){try{return(new Hc).na(A).digest()}catch(G){return null}}function Fb(z){return new v(function(A){setTimeout(A,z)})}function eb(){return Ea(this,void 0,void 0,function*(){pa("compress",B);pa("mutations",ha);pa("reset",Y);pa("irDelete",Sb);pa("SHA-256",ia);yield mc()})}function fb(){return Ea(this,void 0,void 0,function*(){self.postMessage("loaded",void 0);yield Fb(0);yield ua();yield W();yield eb()})}function Wb(){Tc.$(self,function(z,A,G){return Ea(this,void 0,void 0,function*(){if("worker"===z.Z)switch(z.query){case "source-req":Tc.I(self,
new sc({Z:"worker",query:"source",result:`(${"undefined"!=typeof sm&&sm.toString()})();`}),{origin:location.href});break;case "initialize":yield ua(!0),yield eb(),La("workerLoaded");case "initialized":G()}})})}function hc(){}function tb(z,A){return function(){z.apply(A,arguments)}}function Jb(z){if(!(this instanceof Jb))throw new TypeError("Promises must be constructed via new");if("function"!=typeof z)throw new TypeError("not a function");this.pa=0;this.Ob=!1;this.ra=void 0;this.Ea=[];x(z,this)}
function sb(z,A){for(;3===z.pa;)z=z.ra;0===z.pa?z.Ea.push(A):(z.Ob=!0,Jb.sb(function(){var G=1===z.pa?A.Ad:A.Bd;if(null===G)(1===z.pa?Ac:Tb)(A.promise,z.ra);else{try{var fa=G(z.ra)}catch(Ga){Tb(A.promise,Ga);return}Ac(A.promise,fa)}}))}function Ac(z,A){try{if(A===z)throw new TypeError("A promise cannot be resolved with itself.");if(A&&("object"==typeof A||"function"==typeof A)){var G=A.then;if(A instanceof Jb){z.pa=3;z.ra=A;Xb(z);return}if("function"==typeof G){x(tb(G,A),z);return}}z.pa=1;z.ra=A;
Xb(z)}catch(fa){Tb(z,fa)}}function Tb(z,A){z.pa=2;z.ra=A;Xb(z)}function Xb(z){2===z.pa&&0===z.Ea.length&&Jb.sb(function(){z.Ob||Jb.Ub(z.ra)});for(var A=0,G=z.Ea.length;A<G;A++)sb(z,z.Ea[A]);z.Ea=null}function kc(z,A,G){this.Ad="function"==typeof z?z:null;this.Bd="function"==typeof A?A:null;this.promise=G}function x(z,A){var G=!1;try{z(function(fa){G||(G=!0,Ac(A,fa))},function(fa){G||(G=!0,Tb(A,fa))})}catch(fa){G||(G=!0,Tb(A,fa))}}var v=self.Promise,t=Object.create,E=Object.defineProperty,P=Object.getOwnPropertyDescriptor,
O=Object.getOwnPropertyNames,ba=Object.getPrototypeOf,X=Object.prototype.hasOwnProperty,db=(z,A,G,fa)=>{if(A&&"object"==typeof A||"function"==typeof A)for(let Ga of O(A))!X.call(z,Ga)&&Ga!==G&&E(z,Ga,{get:()=>A[Ga],enumerable:!(fa=P(A,Ga))||fa.enumerable});return z},jb=((z,A)=>function(){return A||(0,z[O(z)[0]])((A={exports:{}}).exports,A),A.exports})({["../../node_modules/.pnpm/snappyjs@0.7.0/node_modules/snappyjs/snappy_compressor.js"](z){function A(Gb,Lb){return 506832829*Gb>>>Lb}function G(Gb,
Lb){return Gb[Lb]+(Gb[Lb+1]<<8)+(Gb[Lb+2]<<16)+(Gb[Lb+3]<<24)}function fa(Gb,Lb,Hb){return Gb[Lb]===Gb[Hb]&&Gb[Lb+1]===Gb[Hb+1]&&Gb[Lb+2]===Gb[Hb+2]&&Gb[Lb+3]===Gb[Hb+3]}function Ga(Gb,Lb,Hb,l,r){60>=Hb?(l[r]=Hb-1<<2,r+=1):256>Hb?(l[r]=240,l[r+1]=Hb-1,r+=2):(l[r]=244,l[r+1]=Hb-1&255,l[r+2]=Hb-1>>>8,r+=3);var q=r,F;for(F=0;F<Hb;F++)l[q+F]=Gb[Lb+F];return r+Hb}function Ra(Gb,Lb,Hb,l){return 12>l&&2048>Hb?(Gb[Lb]=1+(l-4<<2)+(Hb>>>8<<5),Gb[Lb+1]=Hb&255,Lb+2):(Gb[Lb]=2+(l-1<<2),Gb[Lb+1]=Hb&255,Gb[Lb+2]=
Hb>>>8,Lb+3)}function gb(Gb){this.Df=Gb}var yb=Array(15);gb.prototype.rh=function(){var Gb=this.Df.length;return 32+Gb+Math.floor(Gb/6)};gb.prototype.Bg=function(Gb){var Lb=this.Df,Hb=Lb.length,l=0,r;var q=Hb;var F=0;do Gb[F]=q&127,q>>>=7,0<q&&(Gb[F]+=128),F+=1;while(0<q);for(r=F;l<Hb;){q=Math.min(Hb-l,65536);var L;var ma=F=void 0;var na,Ma,Va=Lb,ib=l;var qb=q;for(var wb=Gb,jc=r,yc=1;1<<yc<=qb&&14>=yc;)yc+=1;--yc;r=32-yc;"undefined"==typeof yb[yc]&&(yb[yc]=new Uint16Array(1<<yc));yc=yb[yc];for(Ma=
0;Ma<yc.length;Ma++)yc[Ma]=0;Ma=ib+qb;var Gc=ib;var Nb=ib;var Jd=!0;if(15<=qb)for(qb=Ma-15,ib+=1,L=A(G(Va,ib),r);Jd;){var cd=32;var hd=ib;do{if(ib=hd,na=L,F=cd>>>5,cd+=1,hd=ib+F,ib>qb){Jd=!1;break}L=A(G(Va,hd),r);ma=Gc+yc[na];yc[na]=ib-Gc}while(!fa(Va,ib,ma));if(!Jd)break;jc=Ga(Va,Nb,ib-Nb,wb,jc);do{cd=ib;for(Nb=4;ib+Nb<Ma&&Va[ib+Nb]===Va[ma+Nb];)Nb+=1;ib+=Nb;L=cd-ma;cd=wb;hd=jc;for(na=Nb;68<=na;)hd=Ra(cd,hd,L,64),na-=64;if(jc=(64<na&&(hd=Ra(cd,hd,L,60),na-=60),Ra(cd,hd,L,na)),Nb=ib,ib>=qb){Jd=!1;
break}ma=A(G(Va,ib-1),r);yc[ma]=ib-1-Gc;cd=A(G(Va,ib),r);ma=Gc+yc[cd];yc[cd]=ib-Gc}while(fa(Va,ib,ma));if(!Jd)break;ib+=1;L=A(G(Va,ib),r)}r=(Nb<Ma&&(jc=Ga(Va,Nb,Ma-Nb,wb,jc)),jc);l+=q}return r};z.kg=gb}}),ic="undefined"!=typeof window?window:self,Fc="undefined"!=typeof globalThis?globalThis:"undefined"!=typeof window?window:void 0,sc=class z{static G(A){try{if("DT UI Worker Bridge"===A.type){let G=A.Ma;return new z({id:G.id,Z:G.Z,query:G.query,result:G.result})}}catch(G){}}constructor({id:A,Z:G,query:fa,
result:Ga}){A?this.id=A:(z.I++,this.id=z.I);this.Z=G;this.query=fa;this.result=Ga}pf(A){"undefined"==typeof A?this.result=null:this.result=A}Da(){return{type:"DT UI Worker Bridge",Ma:{id:this.id,Z:this.Z,query:this.query,result:this.result}}}};sc.I=0;var Tc=class z{static ja(){z.G||(z.G=new Map)}static $(A,G){z.ja();let fa=z.G.get(A);return fa?fa.push(G):(z.G.set(A,[G]),A.addEventListener("message",function(Ga){let Ra=sc.G(Ga.data);Ra&&(z.G.get(A)||[]).slice(0).forEach(function(gb){gb(Ra,Ga,function(){z.da(A,
gb)})})})),G}static da(A,G){z.ja();A=z.G.get(A)||[];A.splice(A.indexOf(G),1)}static I(A,G,{origin:fa="*",transfer:Ga=[]}={}){G=G.Da();Fa()||Object.prototype.toString.call(A).includes("Worker")?A.postMessage(G,Ga):A.postMessage(G,fa,Ga)}constructor(A){A?this.port=A:(A=new MessageChannel,this.port=A.port1,this.G=A.port2)}vb(A){this.port.onmessage=function({data:G}){(G=sc.G(G))&&A(G)}}send(A,G=[]){this.port.postMessage(A.Da(),G)}},Wc,Oc,Pc,fd,Dc=[],K=new Map,C=new Map,ka=new Set,xa=[],Ha=self.performance||
Date,Oa=Date.now()-Ha.now(),Ba=((z,A,G)=>(G=null!=z?t(ba(z)):{},db(!A&&z&&z.Zh?G:E(G,"default",{value:z,enumerable:!0}),z)))(jb(),1),vb=[[/\u0000/g,"\x00"],[/\u0001/g,"\u0001"],[/\u0002/g,"\u0002"],[/\u0003/g,"\u0003"],[/\u0014/g,"\u0014"],[/\u0004/g,"\u0004"],[/\u0005/g,"\u0005"],[/\u0006/g,"\u0006"],[/\u0011/g,"\u0011"],[/\u0012/g,"\u0012"]],Ta,pb,Cb=0,fc,Kb,Ub,Ec,Bc,vc=class z{constructor(){this.G=[];this.values=[]}add(A,G){let fa=this.G[this.G.length-1];return fa>G||(fa===G&&(this.G.pop(),this.values.pop()),
this.I()===A)?!1:(this.G.push(G),this.values.push(A),!0)}Nc(){return this.G.length?this.G[this.G.length-1]:0}I(){return this.values.length?this.values[this.values.length-1]:null}clear(A){let G=-1;this.G.forEach(function(fa,Ga){fa<A&&(G=Ga)});0<G&&(this.values=this.values.slice(G),this.G=this.G.slice(G))}find(A,G=0,fa=!1){let {from:Ga,eb:Ra}=A,gb={Lb:[],values:[]},yb=-1;return this.G.forEach(function(Gb,Lb){let Hb=this.$({time:Gb,index:Lb,th:G,from:Ga,eb:Ra});Hb&&(gb.Lb.push(Hb.time),gb.values.push(Hb.value));
fa&&Gb<Ga&&(yb=Lb)},this),-1!==yb&&(gb.Lb.unshift(this.G[yb]-Ga),gb.values.unshift(this.values[yb])),gb}static I(A,G){return 0!==G&&"string"==typeof A&&A.length>G}static G(A){return A.from<=A.time&&A.time<A.eb}$(A){let G=this.values[A.index];return z.G(A)&&!z.I(G,A.th)?{time:A.time-A.from,value:G}:null}},uc=class{constructor(z,A){this.name=z.attributeName||"";this.values=new vc;this.ka=z.ka;this.$a=A;this.G=z.Y;this.Nd(z.va,A)}Va(){return this.values.I()}Nd(z,A){let G=ea(this.G);G&&"a"===G.name&&
"href"===this.name&&(z="");"string"==typeof z&&(z=this.I(z));this.Va()!==z&&this.values.add(z,A)&&(this.$a=Math.max(A,this.$a),G&&(G.fb(z),G.fb(A)))}I(z){var A;let G=ea(this.G),fa="value"===this.name&&"input"===(null==G?void 0:G.name)&&"number"===(null===(A=null==G?void 0:G.getAttribute("type"))||void 0===A?void 0:A.Va())?"0":"*";this.ka&&this.ka&32?z=z?z.replace(/./g,"*"):"":this.ka&&this.ka&16&&(z=lb(z,fa));A=G&&G.ka&&G.ka&2;if(A=(G&&G.ka&&G.ka&4||A)&&G)A=this.name,A=!!G.name&&["input","textarea"].includes(G.name.toLowerCase())&&
"value"===A;return A&&(z=lb(z,fa)),z}},ld=Date.prototype.toJSON,ad=class z{static G(A){try{let G=JSON.parse(A);return new z(G.type,{Y:G.Y,nodeName:G.nodeName,namespaceURI:G.namespaceURI,nodeValue:G.nodeValue,attributeName:G.attributeName,va:G.va,ba:G.ba,ia:G.ia,ma:G.ma,ka:G.ka})}catch(G){return null}}constructor(A,G){if(!A||!G)throw Error("Invalid parameters");this.type=A;this.Y=G.Y;this.nodeName=G.nodeName;this.namespaceURI=G.namespaceURI;this.nodeValue=G.nodeValue;this.attributeName=G.attributeName;
this.va=G.va;this.ba=G.ba;this.ia=G.ia;this.ma=G.ma;this.ka=G.ka}Da(){return pc({type:this.type,Y:this.Y,nodeName:this.nodeName,namespaceURI:this.namespaceURI,nodeValue:this.nodeValue,attributeName:this.attributeName,va:this.va,ba:this.ba,ia:this.ia,ma:this.ma,ka:this.ka})}he(){}};ad.I="removeNode";ad.$="updateNode";var Yc=class{constructor(z,A){this.id=z.Y;this.name=z.nodeName;this.Yd=A;if(this.id&&"1"===this.id.split(".").pop()||"css.create"===this.name)this.$d=A-1,xa.includes(this)||xa.push(this);
switch(this.attributes=new Map,this.values=new vc,this.Ib=new vc,this.wb=new vc,this.fe=new vc,this.ed=new vc,this.$a=this.Yd,this.Uc=0,this.ka=z.ka,this.id&&this.name&&(this.Xd=this.id.toString().length+1+this.name.toString().length+1),z.namespaceURI){case "http://www.w3.org/2000/svg":this.type="svg";break;case "http://www.w3.org/1998/Math/MathML":this.type="mathml";break;case "dynatrace-metadata":this.type="dtmeta";break;case "css-stylesheet":this.type="cssstylesheet";break;default:this.type="html"}this.nf(z.ba,
A);this.Tb(z.ia,A);this.Sb(z.ma,A);"string"==typeof z.nodeValue&&this.Nd(z.nodeValue,A);this.id&&z.ba&&this.Lc(this.getParent())&&!z.ia&&this.Lc(this.getParent()).mf(this.id,A);"html"!==this.type&&this.fb(this.type)}Lc(z){return ea(z)}qe(z){if(!this.attributes.has(z.name)){var A=this.ka&&this.ka&2;if(A=this.ka&&this.ka&4||A){{A=z.name;var G;let Ga=this.name||"";"selected"===A&&"option"===Ga.toLowerCase()?A=!0:"checked"===A&&"input"===Ga.toLowerCase()?(A=null===(G=this.getAttribute("type"))||void 0===
G?void 0:G.Va(),A=!!A&&["radio","checkbox"].includes(A+"")):A=!1}}if(A){z=z.$a;var fa;z=new uc(new ad("updateAttribute",{attributeName:"disabled",va:"",ka:1,Y:this.id}),z);"input"===(null===(fa=this.name)||void 0===fa?void 0:fa.toLowerCase())?this.qe(z):(fa=this.Lc(this.getParent()),G=(null==fa?void 0:fa.name)||"",fa&&"optgroup"===G.toLowerCase()&&(fa=fa.Lc(fa.getParent()),G=(null==fa?void 0:fa.name)||""),fa&&"select"===G.toLowerCase()&&fa.qe(z))}else this.attributes.set(z.name,z),this.Ef(z),this.fb(z.name)}}getAttribute(z){return this.attributes.get(z)}Jc(z){void 0!==
z&&(this.$a=Math.max(z,this.$a),(z=this.Lc(this.getParent()))&&z.Jc(this.$a))}Ef(z){this.Uc=Math.max(this.Uc,z.$a);this.Jc(this.Uc)}Va(){return this.values.I()}Nd(z,A){this.ka&&this.ka&2&&(z=lb(z));this.Va()!==z&&this.values.add(z,A)&&(this.Jc(A),this.fb(z),this.fb(A))}getParent(){return this.Ib.I()}nf(z,A){this.getParent()===z||!this.Ib.add(z,A)||(this.Jc(A),this.fb(z),this.fb(A))}Nf(){return this.fe.I()}Tb(z,A){this.Nf()===z||!this.fe.add(z,A)||(this.Jc(A),this.fb(z),this.fb(A))}Lf(){return this.wb.I()}Sb(z,
A){this.Lf()===z||!this.wb.add(z,A)||this.Jc(A)}Kf(){return this.ed.I()}mf(z,A){this.Kf()===z||!this.ed.add(z,A)||this.Jc(A)}Vf(){this.Xd=0}fb(z){let A;"string"==typeof z?A=z:"number"==typeof z?A=z.toString():null===z?A="null":A="";this.Xd+=A.length+1;(z=this.Lc(this.getParent()))&&z.fb(A)}Sg(){return Math.max(this.Uc,this.values.Nc(),this.Ib.Nc(),this.ed.Nc(),this.wb.Nc(),this.fe.Nc())}},td=class z{static G(A){try{let Ga=JSON.parse(A);if(Ga&&"Mutation List"===Ga.type){var G=Ga.Ma,fa=new z(G.time);
for(let Ra of G.entries){let gb=ad.G(Ra);gb&&fa.add(gb)}return fa}}catch(Ga){}}static I(A,G){let fa=new z(G);return A.forEach(function(Ga){fa.add(Ga)}),fa}constructor(A){this.time=A;this.set=[];this.size=this.set.length}add(A){A instanceof ad&&(this.set.push(A),this.size=this.set.length)}Gf(A){this.set=this.set.filter(G=>G instanceof ad&&!A(G));this.size=this.set.length}forEach(A){this.set.forEach(function(G){return G instanceof ad&&A(G)})}Da(){return pc({type:"Mutation List",Ma:{time:this.time,entries:this.set.map(function(A){return A.Da()})}})}},
jd={addNode:function(z,A){var G=new Yc(z,A);K.set(z.Y,G);if("dynatrace-metadata"!==z.namespaceURI||void 0!==z.ba&&!Q(z.ba)){G=ea(z.ia);var fa=ea(z.ma);G&&G.Sb(z.Y,A);fa&&fa.Tb(z.Y,A)}else C.set(G.id,G)},updateNode:function(z,A){let G=ea(z.Y),fa=ea(z.ba),Ga=ea(z.ma),Ra=ea(z.ia);G&&G.id&&(fa&&G.nf(fa.id,A),Ra?(Ra.Sb(G.id,A),G.Tb(z.ia,A)):fa&&fa.mf(G.id,A),Ga&&(Ga.Tb(G.id,A),G.Sb(z.ma,A)),G.Sb(z.ma,A),G.Tb(z.ia,A))},removeNode:Rb,updateNodeValue:function(z,A){let G=ea(z.Y);G&&z.nodeValue&&G.Nd(z.nodeValue,
A)},updateAttribute:function(z,A){let G=ea(z.Y);if(void 0!==G&&z.attributeName){var fa=G.getAttribute(z.attributeName);"undefined"==typeof fa?(fa=new uc(z,A),G.qe(fa)):(fa.Nd(z.va,A),G.Ef(fa))}}},gd=new Uint32Array([1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,
3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298]),Hc=class{constructor(){this.blockSize=64;this.state=new Int32Array(8);this.ja=new Int32Array(64);this.G=
new Uint8Array(128);this.da=this.I=0;this.$=!1;this.reset()}reset(){return this.state[0]=1779033703,this.state[1]=3144134277,this.state[2]=1013904242,this.state[3]=2773480762,this.state[4]=1359893119,this.state[5]=2600822924,this.state[6]=528734635,this.state[7]=1541459225,this.I=0,this.da=0,this.$=!1,this}na(z,A=z.length){if(this.$)throw Error("SHA256: can't update because hash was finished.");let G=0;if(this.da+=A,0<this.I){for(;64>this.I&&0<A;)this.G[this.I++]=z[G++],A--;64===this.I&&(Pa(this.ja,
this.state,this.G,0,64),this.I=0)}for(64<=A&&(G=Pa(this.ja,this.state,z,G,A),A%=64);0<A;)this.G[this.I++]=z[G++],A--;return this}finish(z){if(!this.$){var A=this.da,G=this.I,fa=A/536870912|0;let Ga=A<<3;A=56>A%64?64:128;this.G[G]=128;for(G+=1;G<A-8;G++)this.G[G]=0;this.G[A-8]=fa>>>24&255;this.G[A-7]=fa>>>16&255;this.G[A-6]=fa>>>8&255;this.G[A-5]=fa>>>0&255;this.G[A-4]=Ga>>>24&255;this.G[A-3]=Ga>>>16&255;this.G[A-2]=Ga>>>8&255;this.G[A-1]=Ga>>>0&255;Pa(this.ja,this.state,this.G,0,A);this.$=!0}for(fa=
0;8>fa;fa++)z[4*fa]=this.state[fa]>>>24&255,z[4*fa+1]=this.state[fa]>>>16&255,z[4*fa+2]=this.state[fa]>>>8&255,z[4*fa+3]=this.state[fa]>>>0&255;return this}digest(){let z=new Uint8Array(32);return this.finish(z),z}},le=setTimeout;Jb.prototype.catch=function(z){return this.then(null,z)};Jb.prototype.then=function(z,A){var G=new this.constructor(hc);return sb(this,new kc(z,A,G)),G};Jb.prototype.finally=function(z){var A=this.constructor;return this.then(function(G){return A.resolve(z()).then(function(){return G})},
function(G){return A.resolve(z()).then(function(){return A.reject(G)})})};Jb.all=function(z){return new Jb(function(A,G){function fa(yb,Gb){try{if(Gb&&("object"==typeof Gb||"function"==typeof Gb)){var Lb=Gb.then;if("function"==typeof Lb){Lb.call(Gb,function(Hb){fa(yb,Hb)},G);return}}Ga[yb]=Gb;0===--Ra&&A(Ga)}catch(Hb){G(Hb)}}if(!z||"undefined"==typeof z.length)return G(new TypeError("Promise.all accepts an array"));var Ga=Array.prototype.slice.call(z);if(0===Ga.length)return A([]);for(var Ra=Ga.length,
gb=0;gb<Ga.length;gb++)fa(gb,Ga[gb])})};Jb.allSettled=function(z){return new this(function(A,G){function fa(gb,yb){if(yb&&("object"==typeof yb||"function"==typeof yb)){var Gb=yb.then;if("function"==typeof Gb){Gb.call(yb,function(Lb){fa(gb,Lb)},function(Lb){Ga[gb]={status:"rejected",reason:Lb};0===--Ra&&A(Ga)});return}}Ga[gb]={status:"fulfilled",value:yb};0===--Ra&&A(Ga)}if(!z||"undefined"==typeof z.length)return G(new TypeError(typeof z+" "+z+" is not iterable(cannot read property Symbol(Symbol.iterator))"));
var Ga=Array.prototype.slice.call(z);if(0===Ga.length)return A([]);var Ra=Ga.length;for(G=0;G<Ga.length;G++)fa(G,Ga[G])})};Jb.resolve=function(z){return z&&"object"==typeof z&&z.constructor===Jb?z:new Jb(function(A){A(z)})};Jb.reject=function(z){return new Jb(function(A,G){G(z)})};Jb.race=function(z){return new Jb(function(A,G){if(!z||"undefined"==typeof z.length)return G(new TypeError("Promise.race accepts an array"));for(var fa=0,Ga=z.length;fa<Ga;fa++)Jb.resolve(z[fa]).then(A,G)})};Jb.sb="function"==
typeof setImmediate&&function(z){setImmediate(z)}||function(z){le(z,0)};Jb.Ub=function(z){"undefined"!=typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",z)};v||(v=Jb);(function(){return Ea(this,void 0,void 0,function*(){Fa()?yield fb():(Wb(),ic.dT_.iMod("D"))})})()})();
